train:
  _target_: src.datasets.Dataset_ASVspoof2019_general
  model_type: "aasist"
  dataset_type: train
val:
  _target_: src.datasets.Dataset_ASVspoof2019_general
  model_type: "aasist"
  dataset_type: dev
test:
  _target_: src.datasets.Dataset_ASVspoof2019_general
  model_type: "aasist"
  dataset_type: eval # strange, but ok I guess...