train:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.Dataset_ASVspoof2019_train
val:
  _target_: src.datasets.Dataset_ASVspoof2019_dev
test:
  _target_: src.datasets.ExampleDataset
  input_length: 1024
  dataset_length: 15
  n_classes: 10
  name: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
